# Generated by Django 5.0.3 on 2024-05-05 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinic', '0002_remove_patient_sex_user_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='specialization',
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='specialization',
        ),
        migrations.AddField(
            model_name='nurse',
            name='profile_picture',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='nurse',
            name='working_shift',
            field=models.CharField(choices=[('M', 'Morning'), ('E', 'Evening'), ('N', 'Night')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='completed_appointments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctor',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Clinic.department'),
        ),
        migrations.AddField(
            model_name='nurse',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Clinic.department'),
        ),
    ]
