# Generated by Django 5.0.3 on 2024-05-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinic', '0005_remove_appointment_name_appointment_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
