# Generated by Django 5.0.3 on 2024-05-07 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinic', '0007_remove_appointment_doctor_alter_appointment_patient_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='Doctor',
            new_name='doctor',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Clinic.patient'),
        ),
    ]
