# Generated by Django 5.0.3 on 2024-05-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinic', '0008_rename_doctor_appointment_doctor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='day',
        ),
        migrations.AddField(
            model_name='appointment',
            name='date',
            field=models.DateField(default='2024-12-31'),
        ),
    ]
